name: Build App
on:
  push:
    branches: [ main, dev, fix/requirements.txt ]

  pull_request:
    branches: [ main, dev ]

permissions:
  contents: read

jobs:
  pre-start:
    runs-on: ubuntu-latest
    timeout-minutes: 5
    steps:
      - name: Start Build
        run: |
          echo "Beginning to Build ${{ github.repository }}"

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.12'

  run-build:
    name: Build
    needs: pre-start
    strategy:
      matrix:
        folder: [frontend, backend]
        
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install python dependencies
        run: |
          python -m venv venv
          source venv/bin/activate
          python -m pip install --upgrade pip
          cd apps
          pip install -r requirements.txt

      - name: Set up Node.js 21
        uses: actions/setup-node@v4
        with:
          node-version: 21

      - name: Install dependencies
        run: |
          cd apps/${{ matrix.folder }}
          npm install

      - name: Run Builds
        run: |
          cd apps/${{ matrix.folder }}
          npm run build

