# name: Integration Test
# on:
#   push:
#     branches: [ main, dev, feat/ItineraryBackend ]

# permissions:
#   contents: read

# jobs:
#   pre-start:
#     runs-on: ubuntu-latest
#     timeout-minutes: 5
#     steps:
#       - name: Start Build
#         run: |
#           echo "Beginning to Build ${{ github.repository }}"

#   cypress-test:
#     name: Cypress Test
#     runs-on: ubuntu-latest
#     steps:
#       - name: Checkout
#         uses: actions/checkout@v2

#       - name: Set up Node.js 21
#         uses: actions/setup-node@v4
#         with:
#           node-version: 21

#       - name: Install dependencies
#         run: |
#           cd apps/frontend
#           npm install

#       - name: Start application
#         run: |
#           cd apps/frontend
#           npm run dev &

#       - name: Run Cypress tests
#         run: |
#           cd apps/frontend
#           npx cypress run --browser chrome --config video=false
#         env:
#           NEXT_PUBLIC_SUPABASE_URL: ${{ secrets.NEXT_PUBLIC_SUPABASE_URL}}
#           NEXT_PUBLIC_SUPABASE_ANON_KEY: ${{ secrets.NEXT_PUBLIC_SUPABASE_ANON_KEY}}
#           NEXT_PUBLIC_GOOGLE_API_KEY: ${{ secrets.NEXT_PUBLIC_GOOGLE_API_KEY}}  

name: Integration Test

on:
  push:
    branches: [ main, dev, feat/ItineraryBackend ]

permissions:
  contents: read

jobs:
  pre-start:
    runs-on: ubuntu-latest
    timeout-minutes: 5
    steps:
      - name: Start Build
        run: |
          echo "Beginning to Build ${{ github.repository }}"

  cypress-test:
    name: Cypress Test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Set up Node.js 21
        uses: actions/setup-node@v4
        with:
          node-version: 21

      - name: Install dependencies
        run: |
          cd apps/frontend
          npm install

      - name: Build application
        run: |
          cd apps/frontend
          npm run build

      - name: Start application
        run: |
          cd apps/frontend
          npm start &

      - name: Wait for application to be ready
        run: |
          echo "Waiting for the application to be ready..."
          sleep 20 # Adjust the sleep duration as needed

      - name: Print application logs
        run: |
          cd apps/frontend
          tail -n 100 logs/app.log # Adjust the log file path if needed

      - name: Run Cypress tests
        uses: cypress-io/github-action@v3
        with:
          browser: chrome
          wait-on: "http://localhost:3000"
        env:
          NEXT_PUBLIC_SUPABASE_URL: ${{ secrets.NEXT_PUBLIC_SUPABASE_URL}}
          NEXT_PUBLIC_SUPABASE_ANON_KEY: ${{ secrets.NEXT_PUBLIC_SUPABASE_ANON_KEY}}
          NEXT_PUBLIC_GOOGLE_API_KEY: ${{ secrets.NEXT_PUBLIC_GOOGLE_API_KEY}}
