name: Integration Test
on:
  push:
    branches: [ main, dev ]

  pull_request:
    branches: [ main, dev ]

permissions:
  contents: read

jobs:
  pre-start:
    runs-on: ubuntu-latest
    timeout-minutes: 5
    steps:
      - name: Start Build
        run: |
          echo "Beginning to Build ${{ github.repository }}"

  cypress-test:
    name: Cypress Test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Set up Node.js 21
        uses: actions/setup-node@v4
        with:
          node-version: 21

      - name: Install dependencies
        run: |
          cd apps/frontend
          npm install

      - name: Build application
        run: |
          cd apps/frontend
          npm run build

      - name: Start application
        run: |
          cd apps/frontend
          npm start &

      - name: Run Cypress tests
        uses: cypress-io/github-action@v3
        with:
          browser: chrome
          wait-on: "http://localhost:3000"
        env:
          NEXT_PUBLIC_SUPABASE_URL: ${{ secrets.NEXT_PUBLIC_SUPABASE_URL}}
          NEXT_PUBLIC_SUPABASE_ANON_KEY: ${{ secrets.NEXT_PUBLIC_SUPABASE_ANON_KEY}}
          NEXT_PUBLIC_GOOGLE_API_KEY: ${{ secrets.NEXT_PUBLIC_GOOGLE_API_KEY}}  
