name: Lint Codebase
on:
  push:
    branches: [ main, dev ]
  pull_request:
    branches: [ main, dev ]
    
permissions:
  contents: read

jobs:
  start:
    name: Initial Setup
    runs-on: ubuntu-latest
    timeout-minutes: 5

    steps:
      - name: Start Linting
        run: |
          echo "Beginning to lint ${{ github.repository }}"

  lint-codebase:
    name: Lint Frontend
    runs-on: ubuntu-latest
    needs: start

    strategy:
      matrix:
        folder: [frontend, backend]

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '21.x'  

      - name: Install dependencies
        run: |
          cd apps/${{ matrix.folder }}
          npm install

      - name: Run ESLint
        run: |
          cd apps/${{ matrix.folder }}
          npm run lint

