name: Test Code
on:
  push:
    branches: [ main, dev ]
  pull_request:
    branches: [ main, dev ]
    
permissions:
  contents: read

jobs:
  start:
    name: Initial Setup
    runs-on: ubuntu-latest
    timeout-minutes: 5
    steps:
      - name: Starting Job
        run: |
          echo "Beginning to test ${{ github.repository }}"

  lint-codebase:
    name: Test Frontend/Backend
    runs-on: ubuntu-latest
    needs: start

    strategy:
      matrix:
        folder: [frontend]

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '21.x'  

      - name: Install dependencies
        run: |
          cd apps/${{ matrix.folder }}
          npm ci

      - name: Run Tests
        run: |
          cd apps/${{ matrix.folder }}
          npm run test -- --coverage
          
      - name: Create coverage folder if not exists
        run: mkdir -p ./apps/${{ matrix.folder }}/coverage

      - name: List files in coverage directory
        run: ls -R ./apps/${{ matrix.folder }}/coverage

      - name: Jest Code Coverage
        id: coverageComment
        uses: MishaKav/jest-coverage-comment@main
        with:
          hide-comment: true
          coverage-summary-path: ./apps/${{ matrix.folder }}/coverage/coverage-summary.json

      - name: Check the output coverage
        run: |
          echo "Coverage Percentage - ${{ steps.coverageComment.outputs.coverage }}"
          echo "Coverage Color - ${{ steps.coverageComment.outputs.color }}"
          echo "Summary HTML - ${{ steps.coverageComment.outputs.summaryHtml }}"
          
      - name: Upload coverage reports to Codecov
        uses: codecov/codecov-action@v4.0.1
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          files: ./apps/${{ matrix.folder }}/coverage/*.json
          
      - name: Create the badge
        uses: schneegans/dynamic-badges-action@v1.6.0
        with:
          auth: ${{ secrets.GIST_SECRET }}
          gistID: d5e1d38427eaf6a78fc2ac70d0f50bc6
          filename: jest-coverage-comment__main.json
          label: Coverage
          message: ${{ steps.coverageComment.outputs.coverage }}%
          color: ${{ steps.coverageComment.outputs.color }}
          namedLogo: typescript
